const fs = require('node:fs');
const assert = require('node:assert/strict');
const { JSDOM, VirtualConsole } = require('../../apps/presenter-ui/node_modules/jsdom');
const html = fs.readFileSync(__dirname + '/../../docs/demo/mockups/aosedge-demo-interaction-mockup-2-9.source.html', 'utf8');
const errors = [], timers = [];
const console = new VirtualConsole();
console.on('jsdomError', error => errors.push(error.message));
const dom = new JSDOM(html, { runScripts: 'dangerously', virtualConsole: console, beforeParse(window) {
  window.ResizeObserver = class { observe() {} disconnect() {} };
  window.setTimeout = callback => { timers.push(callback); return timers.length; };
  window.clearTimeout = () => {};
}});
const document = dom.window.document;
const q = selector => { const value = document.querySelector(selector); assert.ok(value, selector); return value; };
const click = selector => q(selector).click();
const body = () => q('[data-popup-body]').textContent;
const escape = () => document.dispatchEvent(new dom.window.KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
assert.equal(errors.length, 0, errors.join('\n'));
assert.ok(html.includes('data:image/jpeg;base64,'));
assert.ok(Buffer.byteLength(html) < 1000000);
assert.ok(!/\b(fetch|WebSocket|XMLHttpRequest)\s*\(/.test(html));
assert.equal(document.querySelectorAll('[data-wire]').length, 3);
for (const path of document.querySelectorAll('[data-wire]')) assert.ok(!/NaN|undefined/.test(path.getAttribute('d')));
for (const kind of ['brake', 'tire', 'cloud', 'brake-service', 'tire-service', 'vdp']) {
  click(`[data-open="${kind}"]`);
  assert.equal(q('[data-shade]').hidden, false);
  assert.equal(q('[data-base]').inert, true);
  assert.ok(body().length > 40);
  escape();
  assert.equal(q('[data-shade]').hidden, true);
  assert.equal(q('[data-base]').inert, false);
  assert.equal(document.activeElement, q(`[data-open="${kind}"]`));
}
for (const team of ['brake', 'tire']) {
  click(`[data-open="${team}"]`);
  click('[data-tab="Records"]');
  assert.equal(document.querySelectorAll('[data-record]').length, 4);
  assert.equal(q('[data-page="-1"]').disabled, true);
  click('[data-page="1"]');
  assert.equal(q('[data-page="1"]').disabled, true);
  const selectedLabel = q('[data-record="5"] strong').textContent;
  click('[data-record="5"]');
  assert.ok(body().includes(selectedLabel));
  click('[data-record-back]');
  assert.ok(q('[data-record="5"]'));
  click('[data-page="-1"]');
  assert.ok(q('[data-record="0"]'));
  click('[data-tab="Overview"]');
  assert.equal(q('[data-reset]').disabled, team === 'tire');
  escape();
}
click('[data-open="cloud"]');
click('[data-tab="Software"]');
for (const name of ['brake-service', 'tire-service', 'vdp']) {
  click(`[data-inventory="${name}"]`);
  assert.ok(body().includes('Aos Cloud inventory'));
  click('[data-inventory-back]');
}
click('[data-tab="Resources"]');
assert.equal(document.querySelectorAll('.aos-chart').length, 2);
assert.ok(body().includes('DMIPS'));
escape();
click('[data-open="brake"]');
click('[data-reset]');
click('[data-cancel-reset]');
assert.ok(body().includes('Inspection recommended'));
click('[data-reset]');
click('[data-confirm-reset]');
assert.ok(body().includes('Waiting for CLEAR'));
escape();
timers.at(-1)();
assert.equal(q('[data-shade]').hidden, true);
assert.equal(q('[data-brake-summary]').textContent, 'Waiting for a new drive');
click('[data-open="brake"]');
assert.ok(body().includes('Waiting for a new drive'));
click('[data-tab="Records"]');
assert.equal(document.querySelectorAll('[data-record]').length, 4);
click('[data-shade]');
assert.equal(q('[data-shade]').hidden, true);
assert.equal(errors.length, 0, errors.join('\n'));
assert.equal(q('.aos-story button').textContent, 'Finish demo');
assert.equal(q('.aos-story [data-open="finish"]').getAttribute('aria-haspopup'), 'dialog');
click('[data-open="finish"]');
assert.equal(q('#aos-popup-title').textContent, 'Finish demo');
assert.equal(q('[data-tabs]').hidden, true);
assert.ok(body().includes('Production is unchanged'));
assert.ok(body().includes('Deprovision'));
click('[data-finish-cancel]');
assert.equal(q('[data-shade]').hidden, true);
assert.equal(document.activeElement, q('[data-open="finish"]'));
click('[data-open="finish"]');
click('[data-finish-confirm]');
assert.ok(body().includes('Finish request confirmed'));
assert.ok(body().includes('leaves all real systems'));
click('[data-finish-cancel]');
click('[data-open="finish"]');
assert.ok(q('[data-finish-confirm]'));
escape();
click('[data-open="cloud"]');
assert.equal(q('[data-tabs]').hidden, false);
assert.ok(body().includes('160 DMIPS'));
escape();
assert.equal(errors.length, 0, errors.join('\n'));
process.stdout.write('PASS: backend/Cloud popups and records, reset preview, Finish confirmation/cancel/acknowledgement/reopen, Escape/focus, embedded icons, no network calls.\n');
