import { useEffect, useState } from "react";
import { Modal } from "../../shared/components/Modal";
import { readBackendObservation } from "../../adapters/local/LocalPresenterReadAdapter";

type Team = "brake" | "tire";
type RecordRow = { backendReceivedAt: string; message: {
  messageType?: string; serviceVersion?: string; unitSystemUid?: string;
  serviceInstance?: { serviceId?: string; subjectId?: string; instance?: number };
  content?: unknown; [key: string]: unknown;
} };
type MockData = { source: "DEMO_MOCK"; vehicleTelemetry: false; unitSystemUid: string;
  counts: { kind?: string; message_type?: string; count: number }[]; records: RecordRow[] };
type Observation = { state: string; team: Team; source: "REAL_BACKEND_HTTP"; observedAt: string;
  observations: { readiness?: { state: string; data?: { ready?: boolean; reason?: string } };
    mockData?: { state: string; data?: MockData } } };

export function BackendEvidence({ team, unitSystemUid }: { team: Team; unitSystemUid?: string }) {
  const [data, setData] = useState<Observation | null>(null);
  const [error, setError] = useState(false);
  const [busy, setBusy] = useState(false);
  const [generation, refresh] = useState(0);
  const [detail, setDetail] = useState<RecordRow | null>(null);
  useEffect(() => {
    setData(null); setError(false); setDetail(null); setBusy(false);
  }, [team, unitSystemUid]);
  useEffect(() => {
    let active = true;
    let timer: ReturnType<typeof setTimeout>;
    const controller = new AbortController();
    const read = async () => {
      if (!unitSystemUid || !active) return;
      if (document.visibilityState !== "hidden") {
        setBusy(true);
        try {
          const value = await readBackendObservation(team, controller.signal) as Observation;
          const mock = value.observations?.mockData?.data;
          if (value.team !== team || value.source !== "REAL_BACKEND_HTTP" || !value.observations
              || (mock && (mock.source !== "DEMO_MOCK" || mock.vehicleTelemetry !== false
                || mock.unitSystemUid !== unitSystemUid || !Array.isArray(mock.records) || !Array.isArray(mock.counts)
                || mock.records.some(row => row.message.unitSystemUid !== unitSystemUid)))) throw new Error("BACKEND_SCOPE_MISMATCH");
          if (active) { setData(value); setError(false); }
        } catch { if (active) setError(true); }
        finally { if (active) setBusy(false); }
      }
      if (active) timer = setTimeout(read, 10000);
    };
    void read();
    return () => { active = false; controller.abort(); clearTimeout(timer); };
  }, [team, unitSystemUid, generation]);
  const mock = data?.observations.mockData?.data;
  const available = !error && data?.observations.mockData?.state === "OBSERVED";
  const total = mock?.counts.reduce((sum, row) => sum + row.count, 0) ?? 0;
  return <section className="studio-cloud" aria-label={`${team} backend evidence`}>
    <div className="studio-panel-title"><h2>Function backend</h2><button disabled={busy || !unitSystemUid} onClick={() => refresh(value => value + 1)}>Refresh backend</button></div>
    <p className="studio-stamp">{busy ? "Reading backend…" : !unitSystemUid ? "Current Test identity not observed in Cloud" : error ? "Backend unavailable · previous records are last known" : `Observed ${data?.observedAt ? new Date(data.observedAt).toLocaleTimeString() : "not yet"}`}</p>
    <div className="studio-mock-notice"><strong>MOCK DATA · Real service → real backend</strong><p>Synthetic inputs generated by the Test service. No KUKSA telemetry or in-vehicle advisory is claimed.</p></div>
    <div className="studio-metrics"><article><small>Backend process</small><strong>{!error && data?.observations.readiness?.data?.ready ? "Ready" : "Not confirmed"}</strong></article>
      <article><small>Stored mock messages{available ? "" : " · last known"}</small><strong>{mock ? total : "Not observed"}</strong></article>
      <article><small>Vehicle data / advisory</small><strong>Not connected</strong></article></div>
    <h3 className="studio-evidence-title">Latest received records{available ? "" : " · last known"}</h3>
    <div className="studio-inventory">{mock?.records.map((row, index) => <button key={`${row.backendReceivedAt}-${index}`} onClick={() => setDetail(row)}>
      <strong>{row.message.messageType ?? "Product message"}</strong><span>Service {row.message.serviceVersion ?? "not reported"} · received {new Date(row.backendReceivedAt).toLocaleTimeString()}</span>
      <small>Current Test · synthetic source · durable backend record</small></button>)}</div>
    {!mock?.records.length && <p>{available ? "No mock records received from this Test service yet." : "No current backend evidence."}</p>}
    {detail && <Modal title="Synthetic product record" subtitle={`${team === "brake" ? "Brake" : "Tire"} backend · MOCK DATA · not vehicle telemetry`} onClose={() => setDetail(null)}>
      <pre className="studio-details">{JSON.stringify(detail, null, 2)}</pre></Modal>}
  </section>;
}
