#!/usr/bin/expect -f

set timeout 30
set password "Password1"

if {$argc == 0} {
    puts stderr "Usage: aosvm-expect-password COMMAND \[ARGUMENT ...\]"
    exit 2
}

spawn {*}$argv
expect {
    -re {(?i)password:} {
        send -- "$password\r"
        exp_continue
    }
    eof {}
    timeout {
        puts stderr "Password-authenticated guest command timed out."
        exit 124
    }
}

catch wait result
set exit_status [lindex $result 3]
if {$exit_status eq ""} {
    exit 1
}
exit $exit_status
